services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    mem_limit: 512m
    environment:
      MONGO_INITDB_ROOT_USERNAME: chau
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })" ]
      interval: 5s
      timeout: 2s
      retries: 60
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: {}